import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@mgorrin/web-kit/design-system/tokens.css";
import "./globals.css";
import { themeCssVariables } from "../../theme.config";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Override por cliente de las variables --color-* de tokens.css — ver theme.config.ts */}
        <style dangerouslySetInnerHTML={{ __html: themeCssVariables() }} />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>{children}</body>
    </html>
  );
}
